// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC98M06KOxdtWaCTiFVruLOE8_jMHlkC68',
    appId: '1:1041212250980:web:3bed115d79eb9e52c67871',
    messagingSenderId: '1041212250980',
    projectId: 'nagrikapp-5a2ee',
    authDomain: 'nagrikapp-5a2ee.firebaseapp.com',
    storageBucket: 'nagrikapp-5a2ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrhbbpCz8pmnaXi6Cy5B7tj_7FV2Prxq8',
    appId: '1:1041212250980:android:018a0344cf99d123c67871',
    messagingSenderId: '1041212250980',
    projectId: 'nagrikapp-5a2ee',
    storageBucket: 'nagrikapp-5a2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKc0eU_quxJ6Wm1usVt5risAGXNrAmgOE',
    appId: '1:1041212250980:ios:fb0dee857af940bdc67871',
    messagingSenderId: '1041212250980',
    projectId: 'nagrikapp-5a2ee',
    storageBucket: 'nagrikapp-5a2ee.firebasestorage.app',
    iosBundleId: 'com.example.nagrikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKc0eU_quxJ6Wm1usVt5risAGXNrAmgOE',
    appId: '1:1041212250980:ios:fb0dee857af940bdc67871',
    messagingSenderId: '1041212250980',
    projectId: 'nagrikapp-5a2ee',
    storageBucket: 'nagrikapp-5a2ee.firebasestorage.app',
    iosBundleId: 'com.example.nagrikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC98M06KOxdtWaCTiFVruLOE8_jMHlkC68',
    appId: '1:1041212250980:web:a4e5c31ccac30061c67871',
    messagingSenderId: '1041212250980',
    projectId: 'nagrikapp-5a2ee',
    authDomain: 'nagrikapp-5a2ee.firebaseapp.com',
    storageBucket: 'nagrikapp-5a2ee.firebasestorage.app',
  );

}